const data = {
  fabrics: [
    {
      id: 1,
      name: '광목',
      // src: 'sample1.jpg',
      species: ['14수', '16수', '20수', '30수', '40수', '60수', '생지'],
      cloths: [
        { 
          cth_id: 1, 
          name: '손수건', 
          size: '50*50(cm)', 
          fabric: '광목',
          species: '60수',
          src: './src/clo1.jpeg',
        },
        { 
          cth_id: 2, 
          name: '손수건', 
          size: '50*50(cm)', 
          fabric: '광목',
          species: '30수',
          src: './src/clo2.jpeg',
        },

        {
          cth_id: 8,
          name: '6단 프릴 속바지',
          size: 'free size', 
          fabric: '광목',
          species: '60수',
          src: './src/clo3.jpeg',
        },
        {
          cth_id: 9,
          name: '4인용 식탁러그',
          size: '27*150(cm)', 
          fabric: '광목',
          species: '16수',
          src: './src/clo4.jpeg',
        },
        {
          cth_id: 10,
          name: '오쿠덮개',
          size: '지름56*높이43(cm)', 
          fabric: '광목',
          species: '16수',
          src: './src/clo6.jpeg',
        },
        { 
          cth_id: 12, 
          name: '핀코 손수건', 
          size: '50*50(cm)',  
          fabric: '광목',
          species: '30수',
          src: './src/clo8.jpeg',
        },
        { cth_id: 6, 
          name: '벽걸이 티슈', 
          size: '29*12(cm)',  
          fabric: '광목',
          species: '16수',
          src: './src/clo13.jpeg',
        },
      ],
      fabric: [
        {
          fab_id: 1,
          name: '광목 자수원단1',
          size: '폭 150(cm)',
          fabric: '광목',
          species: '20수',
          src: './src/fab1.jpeg',
        },
        {
          fab_id: 2,
          name: '광목 자수원단2',
          size: '폭 150(cm)',
          fabric: '광목',
          species: '20수',
          src: './src/fab2.jpeg',
        },
        {
          fab_id: 3,
          name: '광목 자수원단3',
          size: '폭 150(cm)',
          fabric: '광목',
          species: '20수',
          src: './src/fab3.jpeg',
        },
        {
          fab_id: 9,
          name: '광목생지 원단',
          size: '폭 150(cm)',
          fabric: '광목',
          species: '16수, 20수',
          src: './src/gyangmok_natural_color20&16.jpeg',
        },
        {
          fab_id: 10,
          name: '광목16수 원단',
          size: '폭 150(cm)',
          fabric: '광목',
          species: '16수',
          src: './src/gyangmok16.jpeg',
        },
        {
          fab_id: 11,
          name: '광목20수 원단',
          size: '폭 150(cm)',
          fabric: '광목',
          species: '20수',
          src: './src/gyangmok20.jpeg',
        },
        {
          fab_id: 12,
          name: '광목30수 원단',
          size: '폭 150(cm)',
          fabric: '광목',
          species: '30수',
          src: './src/gyangmok30.jpeg',
        },
        // {
        //   fab_id: 13,
        //   name: '광목40수 원단',
        //   size: '폭 150(cm)',
        //   fabric: '광목',
        //   species: '40수',
        //   src: './src/gyangmok40.jpeg',
        // },
        {
          fab_id: 14,
          name: '광목60수 원단',
          size: '폭 150(cm)',
          fabric: '광목',
          species: '60수',
          src: './src/gyangmok60.jpeg',
        },
      ],
    },
    {
      id: 2,
      name: '무명',
      species: ['10수', '17수'],
      cloths: [
        { cth_id: 4, 
          name: '사각다포', 
          size: '42*26(cm)', 
          fabric: '무명',
          species: '10수',
          src: './src/clo9.jpeg',
        },
        { cth_id: 5, 
          name: '원다포', 
          size: '지름 51(cm)',  
          fabric: '무명',
          species: '17수',
          src: './src/clo10.jpeg',
        },
        { cth_id: 13, 
          name: '작은 원다포', 
          size: '지름 26(cm)',  
          fabric: '무명',
          species: '17수',
          src: './src/clo11.jpeg',
        },
        { 
          cth_id: 3, 
          name: '사각티슈', 
          size: '23*12(cm)',  
          fabric: '무명',
          species: '10수',
          src: './src/clo12.jpeg',
        },
        {
          cth_id: 11,
          name: '주방 손수건',
          size: '밑면31*높이43(cm)', 
          fabric: '무명',
          species: '17수',
          src: './src/clo7.jpeg',
        },
        {
          cth_id: 15,
          name: '미니 가방',
          size: '지름17*높이26(cm)', 
          fabric: '무명',
          species: '무명',
          src: './src/clo14.jpeg',
        }
      ],
      fabric: [
        {
          fab_id: 7,
          name: '무명17수 원단',
          size: '폭 150(cm)',
          fabric: '무명',
          species: '10수',
          src: './src/mumyung17.jpeg',
        },
        {
          fab_id: 8,
          name: '무명10수 원단',
          size: '폭 115(cm)',
          fabric: '무명',
          species: '10수',
          src: './src/mumyung10.jpeg',
        },
      ],
    },
    {
      id: 3,
      name: '인견',
      species: ['생지'],
      cloths: [
        { 
          cth_id: 7, 
          name: '파자마', 
          fabric: '인견', 
          species: '가공지',
          size: 'free size',
          src: './src/clo5.jpeg',
        },
      ],
      fabric: [
        {
          fab_id: 4,
          name: '인견생지 원단1',
          size: '폭 160(cm)',
          fabric: '인견',
          species: '생지',
          src: './src/ingyen_sangzi1.jpeg',
        },
        {
          fab_id: 5,
          name: '인견생지 원단2',
          size: '폭 160(cm)',
          fabric: '인견',
          species: '생지',
          src: './src/ingyen_sangzi2.jpeg',
        },
        {
          fab_id: 6,
          name: '인견생지 원단3',
          size: '폭 160(cm)',
          fabric: '인견',
          species: '생지',
          src: './src/ingyen_sangzi3.jpeg',
        },
      ],
    },
    { id: 4, name: '자가드', species: ['가공지'], cloths: [], fabric: [
      {
        fab_id: 15,
        name: '자가드 원단',
        size: '폭 150(cm)',
        fabric: '자가드',
        species: '가공지',
        src: './src/jagad.jpeg',
      },
    ]},
    { id: 5, name: '면실크', species: ['가공지'], cloths: [], fabric: [
      {
        fab_id: 17,
        name: '면실크 원단',
        size: '폭 150(cm)',
        fabric: '면실크',
        species: '가공지',
        src: './src/myeonsilk.jpeg',
      },
    ]},
    { id: 6, name: '슬라브', species: ['가공지'], cloths: [], fabric: [
      {
        fab_id: 18,
        name: '슬라브 원단',
        size: '폭 150(cm)',
        fabric: '슬라브',
        species: '가공지',
        src: './src/slave.jpeg',
      },
    ] },
    { id: 7, name: '기타', cloths: [
      {
        cth_id: 14,
        name: '손수건',
        size: '50*50(cm)',
        fabric: '기타',
        species: '혼합',
        src: './src/clo15.jpeg',
        msg: '무늬는 가공할 때 마다 바뀔 수 있습니다.',
      },
    ]},
  ],
};

export default data;
